# This file is copied from
# * https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/intro/spring/deployment/src/main/resources/application.yml

jsf:
  projectStage: Production

# Note: no need to specify URL of database, as Heroku will
# automatically set environmental variables used by Spring

spring:
  datasource:
    username: "postgres"
    password: "postgres"
    url: "jdbc:postgresql://db:5432/postgres"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: "validate"
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
