version: '3.5'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
     - "/srv/docker/enterprise/postgres/:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  web:
    image: exam/frontend
    ports:
      - "8080:8080"
    depends_on:
     - db
